#!/usr/bin/env bash
# Push from client a file

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello world!" > > /etc/nginx/html/index.html
sed -i "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
