#!/usr/bin/env bash
#This script installs and configures Nginx on a brand new Ubuntu machine
#so that its HTTP response contains a custom header named X-Served-By,
#with the value being the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx

# Index page
echo "Hello World" >/var/www/html/index.nginx-debian.html

#Configure Nginx to add the custom header
sed -i /listen \[::\]:80 default_server;/a\
rewrite ^\/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;
/etc/nginx/sites-available/default

# 404 Page not Found
curl https://pastebin.com/raw/szLjiB9Q >/var/www/html/404.html
sed -i /dQw4w9WgXcQ permanent;$/a\
error_page 404 /404.html;
/etc/nginx/sites-available/default

# Served header
sed -i "/404 \/404.html;$/a\
add_header X-Served-By $(ubuntu);" /etc/nginx/sites-available/default

#Restart Nginx to apply the changes
service nginx restart
