#!/usr/bin/env bash

#This script displays listening port

listening_ports=$(netstat -tuln | awk '/^tcp/ || /^udp/')

# Print the header
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Print listening ports and their details
echo "$listening_ports"

# Print separator for better readability
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Use netstat to display listening UNIX domain sockets and their PIDs
unix_sockets=$(netstat -lx | grep "^unix")

# Print listening UNIX domain sockets and their details
echo "$unix_sockets"
