#!/usr/bin/env bash

#This script displays listening port

# Show active connections (TCP and UDP)
printf "Active Internet connections (only servers)\n"
printf "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name\n"
ss -tnlp -H | awk '{print $1, $2, $3, $4, $5, $6, $NF}' | grep 'LISTEN' | column -t

# Show active Unix domain sockets (optional)
printf "\nActive UNIX domain sockets (only servers)\n"
printf "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path\n"
ss -Uanp | awk '{print $1, $2, $3, $4, $5, $6, $NF}' | grep 'LISTEN' | column -t
