#!/usr/bin/env bash
# This script stops the "4-to_infinity_and_beyond process" using kill.

process_pid=$(pgrep 4-to_infinity_and_beyond)
if [ -n "$process_pid" ]; then
    kill -TERM "$process_pid"
fi
