#!/usr/bin/env bash

# This script stops the process named "4-to-infinity_and_beyond" without using kill or killall.


process_pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$process_pid" ]; then
    kill -15 "$'process_pid"
    echo "Process stopped successfully."
else
    echo "Process not found."
fi
