#!/usr/bin/env bash
#a Bash script that displays the user name ,user ID and home directory path
#for each user in the /etc/passwd file using a while loop

while IFS=: read -r username _ uid _ home _;
	do
		echo "Username: $username"
		echo "User ID: $uid"
		echo "Home Directory: $home"
	done < /etc/passwd
