#!/usr/bin/env bash
#This script displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed
#using for loop

for file in *
do
	if [ -f "$file" ] && [[ $file != .* ]]
		# Check if file is a regular file and not hidden
	then
		filename=$(echo "$file" | cut -d '-' -f2-)
		# Extract part of filename after the first dash
		printf "%s\n" "$filename" # Print filename
	fi
done
