#!/usr/bin/env bash

#This script checks if the school file exists, is empty, and is a regular file.
if [ -e "school" ] # Check if file exists
then
	echo "school file exists"
	if [ -s "school" ] # Check if file is not empty
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]  #Check if file is a regular file
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
