#!/usr/bin/env bash

# This script configures Nginx to run as the 'nginx' user and listen on port 8080
sudo pkill apache2
sleep 2
sudo chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
