#!/usr/bin/env bash
#To configure the SSH client to use the private key ~/.ssh/school
#and refuse authentication using a password
#This configuration sets 52.86.43.1 host
#to use the private key ~/.ssh/school for authentication
#and refuses to authenticate using a password
#The line thirteen and fourteen command appends the configuration settings
#to the ~/.ssh/config file
#line fifteen command sets the file's permissions
#to only allow the current user to read and write to it
Host 52.86.43.1
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
echo -e "52.86.43.1\n\tIdentityFile
~/.ssh/school\n\tPasswordAuthentication no\n" >> ~/.ssh/config
chmod 600 ~/.ssh/config
